---
title: "Syllabus"
output: html_document
---

```{r setup, include=FALSE}
source("./_aux/links_supplementary.R")
```


# Course Syllabus

::: {#overview .container .sec}
## Course Learning Outcomes

The course introduces fundamental tools in mathematics and computer science that are crucial for subsequent studies, work, and research. Among the topics that will be studied:

  - How to communicate clearly and concisely (mathematical language): Propositional logic, set theory, operations on formulae and on sets.
  - How to count (combinatorics and discrete probability): Combinations and permutations, notions in discrete probability, conditional probability, independence, linearity of expectation.

The exercises in the course emphasize problem-solving and mathematical rigor. We will also practice proof techniques such as induction, contradiction, and counter-example.

  - **Prerequisites:** Grade 12 Calculus and Vectors and one other Grade 12 mathematics course
  - **Corequisites:** None
  - **Exclusions:** MATA67H3, (CSCA65H3), CSC165H, CSC240H, MAT102H
  - **Recommended Preparation:** CSCA08H3 or CSCA20H3
  - **Credit Value:** 0.5
:::

::: {#syltextbook .container .sec}
## Textbooks

  Discrete Mathematics and Its Applications, 8th edition, Kenneth Rosen, 2019, McGraw-Hill Education
:::

::: {#sylassessment .container .sec}
## Assessment and Deadlines

  - **Assignments (15%)**
    - There will be 6 assignments. The top 5 grades will contribute 15% to your final grade (each one is worth 3%).
    - Assignments are to be solved and submitted individually to [Crowdmark](`r crowdmark_l`).
    - Don't use any software or online tools (*e.g.*, WolframAlpha, ChatGPT, etc.) for solving weekly assignments.
  - **Quizzes (10%)**
    - There will be multiple pop quizzes. These quizzes will be published on Crowdmark during the lectures and are due by the end of the day.
    - These quizzes will be graded based on a pass/fail grading system. The two lowest grade quizzes will be dropped and the remaining ones will contribute 10% to your final grade.
    - Quizzes are to be solved and submitted individually to [Crowdmark](`r crowdmark_l`).
  - **Term Tests (30%)**
    - There will be two 2 equally weighted Term Tests.
      - **Term Test 1:** 2024-06-14 (Friday, 2:10-3 PM, During lecture time, in class)
      - **Term Test 2:** 2024-07-19 (Friday, 2:10-3 PM, During lecture time, in class)
    - The lowest term test score will be replaced by the final exam score if the latter is greater than the former. For instance, if you get 25% on term test 1 (had a bad day!), 85% on term test 2, and 75% on the final exam, then a term test 1 score of 75% would be used to compute your course grade.
    - There will be no make-up term tests. Exceptions are considered only for extraordinary and well documented reasons. Remedies for such exceptions may entail an oral test that is harder than the one that was missed.
    - Term Tests are to be solved individually, without use of any device or aid (*i.e.*, the exams will be closed book and calculators and aid sheet are NOT allowed).
  - **Final Exam (45%)**
    - The final exam is closed book, comprehensive, 3 hours, and held during 
    the exam period.
    - Calculators and aid sheet are NOT allowed.

All (currently tentative) deadlines are listed in the [schedule](#schedule). 
Note that **due dates may change** based on how the course is progressing.
:::

::: {#sylintegrity .container .sec}
## Academic Integrity

  The University treats cases of cheating and plagiarism very seriously. The University of Toronto's [Code of Behaviour on Academic Matters](http://www.governingcouncil.utoronto.ca/policies/behaveac.htm) outlines the behaviours that constitute academic dishonesty and the processes for addressing academic offences.
  
Potential offences in papers and assignments include using someone else's ideas or words without appropriate acknowledgement, submitting your own work in more than one course without the permission of the instructor, making up sources or facts, obtaining or providing unauthorized assistance on any assignment.

On tests and exams, cheating includes using or possessing unauthorized aids, looking at someone else's answers during an exam or test, misrepresenting your identity, or falsifying or altering any documentation required by the University.

All of the work you submit must be done by you, and your work must not be submitted by someone else. Plagiarism is academic fraud and is taken very seriously. The department uses software that compares programs for evidence of similar code. Please read the Rules and Regulations from the U of T Governing Council, especially the Code of Behaviour on Academic
Matters.

Please also see the information for students from the Office of Student Academic Integrity.

Please don't copy. We want you to succeed and are here to help. The simplest advice for avoiding plagiarism is:

  - Never look at another student's assignment solution, whether it is on paper or on the computer screen. Never show another student your assignment solution. This applies to all drafts of a solution and to incomplete solutions.
  
  - If you find code/help/solution on the web that solves part or all of an assignment, do not use or submit any part of it. A large percentage of the academic offences in CS involve students who have never met, and who just happened to find the same solution online. If you find a solution, someone else will too.

  - Be very careful when engaging "tutoring services". In previous years, we had students suspended from the university as a result of submitting work that was done with the "help" of such "tutors". When in doubt whether a tutoring company is offering real teaching or is helping students cheat, do not hesitate to ask your instructor — we are here to help!
:::

::: {#sylplagiarism .container .sec}
## Plagiarism Detection

Normally, students will be required to submit their course essays to the University's plagiarism detection tool for a review of textual similarity and detection of possible plagiarism. In doing so, students will allow their essays to be included as source documents in the tool's reference database, where they will be used solely for the purpose of detecting plagiarism. The terms that apply to the University's use of this tool are described on the [Centre for Teaching Support & Innovation](https://teaching.utoronto.ca/resources/plagiarism-detection/) web site.

Students may wish to opt out of using the plagiarism detection tool. In order to opt out, contact your instructor by email no later than two (2) weeks after the start of classes. If you have opted out, then specific information on an alternative method to submit your assignment can be found below.
:::

::: {#sylconsent .container .sec}
## Informed Consent -- Email Lists

As a student enrolled in this course, you understand that you are providing your implicit consent to be included in an email list for the department to send you non-essential information from time to time. If you do not wish to be included in such an email list, please request to be removed by contacting one of the Academic Advisors & Undergraduate Program Administrators. Their information can be found on the MCS Website Contact Us [page](https://www.utm.utoronto.ca/math-cs-stats/contact-us-outreach).
:::

::: {#sylmissterm .container .sec}
## Missed Term Work

In general, if work is missed due to an emergency situation, then the weight of the work will be placed on other similar components in the course. For example, a missed term test would add to the weight of the final exam, and a missed assignment would add to the weight of a later assignment. Exact accommodation will be discussed between the student and the instructor, who must be informed within 72 hours of the due date.
:::


::: {#sylremark .container .sec}
## Remark Requests

Remark requests are due within 1 week of receiving the graded work and must be submitted by posting a private note on Piazza.

  - We ask that you carefully review your assignments, reflect, and write a short explanation justifying the reasons for a regrading request.
  - If a grade is contested and we realize that the marker made a mistake in the student's favour, the mark for that assignment may be lowered when the mistake is found. This would otherwise create a situation which is unfair to other students.
  - Please include your full name and UTORid in the body of the private note.
:::

::: {#sylaccommodations .container .sec}
## Accommodations

  Students with diverse learning styles and needs are welcome in this course. In particular, if you have a disability/health consideration that may require accommodations, please feel free to approach me and/or the AccessAbility Services Office as soon as possible.
  
  AccessAbility Services staff (located in Rm AA142, Arts and Administration Building) are available by appointment to assess specific needs, provide referrals and arrange appropriate accommodations 416-287-7560 or email ability.utsc@utoronto.ca. The sooner you let us know your needs the quicker we can assist you in achieving your learning goals in this course.
:::

::: {#sylspecconsider .container .sec}
## Special Consideration

Please contact us immediately if you cannot complete coursework or miss a test due to a major illness or other circumstances outside your control. Special consideration will be evaluated on a case-by-case basis and is not given automatically. We may be unable to grant you exactly the special consideration you seek, so please ensure we have time to discuss your situation.

In order to receive special consideration, you must fill out a Request for Special Consideration Form. Submit the form in PDF format as soon as possible, together with any supporting documentation, to the course instructor's email address.

You can contact us (by email using the course instructor's email address) even before you have your documentation ready to submit; we won't be able to tell you at that point what accommodation you may receive, but we can answer other questions and offer advice. It is always easier to resolve situations earlier rather than later. If you face a particularly disruptive situation that is likely to impact more than one course, please contact your College Registrar. They are best equipped to provide you with general advice and support that goes beyond a single course.
:::


::: {#syledi .container .sec}
## Equity, Diversity and Inclusion
The University of Toronto is committed to equity, human rights and respect for diversity. All members of the learning environment in this course should strive to create an atmosphere of mutual respect where all members of our community can express themselves, engage with each other, and respect one another's differences. U of T does not condone discrimination or harassment against any persons or communities. 

The University of Toronto is a richly diverse community and as such is committed to providing an environment free of any form of harassment, misconduct, or discrimination. In this course, I seek to foster a civil, respectful, and open-minded climate in which we can all work together to develop a better understanding of key questions and debates through meaningful dialogue. As such, I expect all involved with this course to refrain from actions or behaviours that intimidate, humiliate, or demean persons or groups or that undermine their security or self-esteem based on traits related to race, religion, ancestry, place of origin, colour, ethnic origin, citizenship, creed, sex, sexual orientation, gender identity, gender expression, age, marital status, family status, disability, receipt of public assistance or record of offences.
:::


::: {#syllec .container .sec}
## Lectures
You are expected to attend lecture every week. Lectures will be recorded by the AuRA (Auto-mated Recording Apparatus) service. It uses an AI powered camera. As with all new technoogy, it would be foolish to rely on it. You should arrange for a classmate to share notes with you if you cannot attend a lecture.
:::


::: {#syltut .container .sec}
## Tutorials
You are expected to attend your assigned tutorial every week. Tutorials will not be recorded. You should arrange for a classmate to share notes with you if you cannot attend a tutorial.
:::

::: {#sylannounce .container .sec}
## Course Announcements
All course announcements will be posted on Piazza. You are responsible for reading all postings made by the instructor or the TAs on Piazza and for being familiar with the entire content of this Syllabus; please take a few minutes at the beginning of the term to read through the entire Syllabus.
:::

::: {#syldisc .container .sec}
## Discussion Board
  - For all questions of general interest (whose answers are likely to be useful to other students, e.g., about the course material, assignments, general questions about course logistics and administration), where you can ask the question while respecting the academic integrity of the course (without revealing any idea or part of a solution to a course assessment), please start a new topic directly on the Piazza discussion forum, so that everyone can benefit from reading your questions and the associated answers. We will monitor the forum regularly, but feel free to answer questions from other students, too! Helping someone else learn is one of the most effective ways to master a subject.
  - For personal questions (making appointments, remarking requests, etc.), please email the course instructor directly from your University of Toronto email address. Please include "A67" in the subject line and your full name and UTORid in the body of the email. Otherwise, your message might be marked as spam!
:::

::: {#sylcommunication .container .sec}
## Communications 
It is the student's responsibility to:

  - Maintain current contact information with the University, including address, phone numbers, and emergency contact information.
  - Use the university-provided e-mail address or maintain a valid forwarding e-mail address.
  - Regularly check the official University communications channels. Official University communications are considered received if sent by postal mail, fax, or e-mail to the student's designated primary e-mail account via their @utoronto.ca alias.
  - Accept that forwarded e-mails may be lost and that e-mail is considered received if sent via the student's @utoronto.ca alias.
  - Check the UofT/Quercus email and course websites on a regular basis during the term. Further, check the discussion board daily for any course updates/announcements.
  - Read and keep current with the discussions on the discussion board.
:::

::: {#sylvid .container .sec}
## Video Recording and Sharing (Download and Re-use Prohibited)

  This course, including your participation, will be recorded on video and will be available to students in the course for viewing remotely and after each session.
  
  Course videos and materials belong to your instructor, the University, and/or other sources depending on the specific facts of each situation and are protected by copyright. Do not download, copy, or share any course or student materials or videos without the explicit permission of the instructor.
  
  For questions about the recording and use of videos in which you appear, please contact your instructor.
:::

::: {#syllandack .container .sec}
## University Land Acknowledgement

  I wish to acknowledge this land on which the University of Toronto operates. For thousands of years, it has been the traditional land of the Huron-Wendat, the Seneca, and the Mississaugas of the Credit. Today, this meeting place is still the home to many Indigenous people from across Turtle Island and we are grateful to have the opportunity to work on this land.
:::