course_code <- "CSC(MAT)A67"
course_full_name <- "Discrete Mathematics"
university <- "University of Toronto Scarborough"
department <- "Computer & Mathematical Science"
season <- "Summer"
year <- "2024"

zoom_lec_l <- "https://utoronto.zoom.us/j/83250464222"
quercus_l <- "https://q.utoronto.ca/courses/348221"
crowdmark_l <- "https://crowdmark.com"